package com.ssmssm.dao.system;

import com.ssmssm.core.annotation.MyBatisRepository;
import com.ssmssm.entity.system.CommonCode;
import com.ssmssm.entity.system.CommonCodeCriteria;
import com.ssmssm.entity.system.CommonCodeKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface CommonCodeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    int countByExample(CommonCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    int deleteByExample(CommonCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    int deleteByPrimaryKey(CommonCodeKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    int insert(CommonCode record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    int insertSelective(CommonCode record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    List<CommonCode> selectByExample(CommonCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    CommonCode selectByPrimaryKey(CommonCodeKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommonCode record, @Param("example") CommonCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommonCode record, @Param("example") CommonCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommonCode record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    int updateByPrimaryKey(CommonCode record);
}