package com.ssmssm.dao.system;

import com.ssmssm.core.annotation.MyBatisRepository;
import com.ssmssm.entity.system.Role;
import com.ssmssm.entity.system.RoleCriteria;
import com.ssmssm.entity.system.RoleKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface RoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    int countByExample(RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    int deleteByExample(RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    int deleteByPrimaryKey(RoleKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    List<Role> selectByExample(RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    Role selectByPrimaryKey(RoleKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role
     * @mbggenerated
     */
    int updateByPrimaryKey(Role record);
}