package com.ssmssm.dao.system;

import com.ssmssm.core.annotation.MyBatisRepository;
import com.ssmssm.entity.system.RoleResource;
import com.ssmssm.entity.system.RoleResourceCriteria;
import com.ssmssm.entity.system.RoleResourceKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface RoleResourceMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    int countByExample(RoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    int deleteByExample(RoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    int deleteByPrimaryKey(RoleResourceKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    List<RoleResource> selectByExample(RoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    RoleResource selectByPrimaryKey(RoleResourceKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoleResource record, @Param("example") RoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoleResource record, @Param("example") RoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleResource record);
}