package com.ssmssm.dao.system;

import com.ssmssm.core.annotation.MyBatisRepository;
import com.ssmssm.core.dao.BaseDao;
import com.ssmssm.entity.system.User;
import com.ssmssm.entity.system.UserCriteria;
import com.ssmssm.entity.system.UserKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface UserMapper extends BaseDao{

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    int countByExample(UserCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    int deleteByExample(UserCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    List<User> selectByExample(UserCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    User selectByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    int updateByExample(@Param("record") User record, @Param("example") UserCriteria example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
}