CREATE TABLE T_SYS_BLOB_FILE
(
    ID                            VARCHAR(32) NOT NULL,
    BLOB_FILE_NAME                VARCHAR(60) NOT NULL,
    MODEL_NAME                    VARCHAR(500) NOT NULL,
    ACTION_TYPE                   VARCHAR(500) NOT NULL,
    SYSTEM_RESERVE1               VARCHAR(200),
    SYSTEM_RESERVE2               VARCHAR(200),
    SYSTEM_RESERVE3               VARCHAR(200),
    SYSTEM_RESERVE4               VARCHAR(32),
    SYSTEM_RESERVE5               VARCHAR(200),
    DEL_FLG                       VARCHAR(1) NOT NULL,
    SYS_REG_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_REG_USR_CD                VARCHAR(30) NOT NULL,
    SYS_UPD_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_UPD_USR_CD                VARCHAR(30) NOT NULL
)
;
ALTER TABLE T_SYS_BLOB_FILE
    ADD CONSTRAINT PK_T_SYS_FILEUPLOAD PRIMARY KEY  (ID)
;
COMMENT ON TABLE T_SYS_BLOB_FILE IS 'BLOB文件'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.ID IS 'BLOB文件ID'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.BLOB_FILE_NAME IS 'BLOB文件名称'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.MODEL_NAME IS '模块名称'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.ACTION_TYPE IS '操作类型'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.SYSTEM_RESERVE1 IS '系统预留1'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.SYSTEM_RESERVE2 IS '系统预留2'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.SYSTEM_RESERVE3 IS '系统预留3'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.SYSTEM_RESERVE4 IS '系统预留4'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.SYSTEM_RESERVE5 IS '系统预留5'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.DEL_FLG IS '删除区分||0:有效 1：无效(逻辑删除)'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.SYS_REG_TMSP IS '登录时间'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.SYS_REG_USR_CD IS '登录者'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.SYS_UPD_TMSP IS '更新时间'
;
COMMENT ON COLUMN T_SYS_BLOB_FILE.SYS_UPD_USR_CD IS '更新者'
;
CREATE TABLE T_SYS_COMMON_CODE
(
    ID                            VARCHAR(32) NOT NULL,
    CODE_ID                       NUMERIC(6,0) NOT NULL,
    CODE_DTL_ID                   NUMERIC(4,0) NOT NULL,
    PARENT_CODE_ID                NUMERIC(10,0) NOT NULL,
    CODE_DTL_NAME                 VARCHAR(120) NOT NULL,
    SYSTEM_RESERVE1               VARCHAR(200),
    SYSTEM_RESERVE2               VARCHAR(200),
    SYSTEM_RESERVE3               VARCHAR(200),
    SYSTEM_RESERVE4               VARCHAR(32),
    SYSTEM_RESERVE5               VARCHAR(200),
    DEL_FLG                       VARCHAR(1) NOT NULL,
    SYS_REG_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_REG_USR_CD                VARCHAR(30) NOT NULL,
    SYS_UPD_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_UPD_USR_CD                VARCHAR(30) NOT NULL
)
;
ALTER TABLE T_SYS_COMMON_CODE
    ADD CONSTRAINT PK_T_SYS_COMMON_CODE PRIMARY KEY  (ID)
;
COMMENT ON TABLE T_SYS_COMMON_CODE IS '共通CODE'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.ID IS '共通CODEID'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.CODE_ID IS '共通CODE'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.CODE_DTL_ID IS '共通明细CODE'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.PARENT_CODE_ID IS '父共通CODE'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.CODE_DTL_NAME IS '共通CODE名称'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.SYSTEM_RESERVE1 IS '系统预留1'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.SYSTEM_RESERVE2 IS '系统预留2'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.SYSTEM_RESERVE3 IS '系统预留3'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.SYSTEM_RESERVE4 IS '系统预留4'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.SYSTEM_RESERVE5 IS '系统预留5'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.DEL_FLG IS '删除区分||0:有效 1：无效(逻辑删除)'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.SYS_REG_TMSP IS '登录时间'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.SYS_REG_USR_CD IS '登录者'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.SYS_UPD_TMSP IS '更新时间'
;
COMMENT ON COLUMN T_SYS_COMMON_CODE.SYS_UPD_USR_CD IS '更新者'
;
CREATE TABLE T_AUTH_ROLE
(
    ID                            VARCHAR(32) NOT NULL,
    ROLE_NAME                     VARCHAR(60) NOT NULL,
    ROLE_ENABLED                  NUMERIC(4,0) NOT NULL,
    COMMENTS                      VARCHAR(300),
    SYSTEM_RESERVE1               VARCHAR(200),
    SYSTEM_RESERVE2               VARCHAR(200),
    SYSTEM_RESERVE3               VARCHAR(200),
    SYSTEM_RESERVE4               VARCHAR(32),
    SYSTEM_RESERVE5               VARCHAR(200),
    DEL_FLG                       VARCHAR(1) NOT NULL,
    SYS_REG_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_REG_USR_CD                VARCHAR(30) NOT NULL,
    SYS_UPD_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_UPD_USR_CD                VARCHAR(30) NOT NULL
)
;
ALTER TABLE T_AUTH_ROLE
    ADD CONSTRAINT PK_T_AUTH_ROLE PRIMARY KEY  (ID)
;
COMMENT ON TABLE T_AUTH_ROLE IS '角色'
;
COMMENT ON COLUMN T_AUTH_ROLE.ID IS '角色ID'
;
COMMENT ON COLUMN T_AUTH_ROLE.ROLE_NAME IS '角色名称'
;
COMMENT ON COLUMN T_AUTH_ROLE.ROLE_ENABLED IS '角色有效'
;
COMMENT ON COLUMN T_AUTH_ROLE.COMMENTS IS '备注'
;
COMMENT ON COLUMN T_AUTH_ROLE.SYSTEM_RESERVE1 IS '系统预留1'
;
COMMENT ON COLUMN T_AUTH_ROLE.SYSTEM_RESERVE2 IS '系统预留2'
;
COMMENT ON COLUMN T_AUTH_ROLE.SYSTEM_RESERVE3 IS '系统预留3'
;
COMMENT ON COLUMN T_AUTH_ROLE.SYSTEM_RESERVE4 IS '系统预留4'
;
COMMENT ON COLUMN T_AUTH_ROLE.SYSTEM_RESERVE5 IS '系统预留5'
;
COMMENT ON COLUMN T_AUTH_ROLE.DEL_FLG IS '删除区分||0:有效 1：无效(逻辑删除)'
;
COMMENT ON COLUMN T_AUTH_ROLE.SYS_REG_TMSP IS '登录时间'
;
COMMENT ON COLUMN T_AUTH_ROLE.SYS_REG_USR_CD IS '登录者'
;
COMMENT ON COLUMN T_AUTH_ROLE.SYS_UPD_TMSP IS '更新时间'
;
COMMENT ON COLUMN T_AUTH_ROLE.SYS_UPD_USR_CD IS '更新者'
;
CREATE TABLE T_AUTH_ROLE_RESOURCE
(
    ID                            VARCHAR(32) NOT NULL,
    ROLE_ID                       VARCHAR(32) NOT NULL,
    RESOURCE_ID                   VARCHAR(32) NOT NULL,
    SYSTEM_RESERVE1               VARCHAR(200),
    SYSTEM_RESERVE2               VARCHAR(200),
    SYSTEM_RESERVE3               VARCHAR(200),
    SYSTEM_RESERVE4               VARCHAR(32),
    SYSTEM_RESERVE5               VARCHAR(200),
    DEL_FLG                       VARCHAR(1) NOT NULL,
    SYS_REG_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_REG_USR_CD                VARCHAR(30) NOT NULL,
    SYS_UPD_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_UPD_USR_CD                VARCHAR(30) NOT NULL
)
;
ALTER TABLE T_AUTH_ROLE_RESOURCE
    ADD CONSTRAINT PK_T_AUTH_ROLE_RESOURCE PRIMARY KEY  (ID)
;
COMMENT ON TABLE T_AUTH_ROLE_RESOURCE IS '角色资源关联'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.ID IS '角色资源关联'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.ROLE_ID IS '角色ID'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.RESOURCE_ID IS '资源节点ID'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.SYSTEM_RESERVE1 IS '系统预留1'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.SYSTEM_RESERVE2 IS '系统预留2'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.SYSTEM_RESERVE3 IS '系统预留3'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.SYSTEM_RESERVE4 IS '系统预留4'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.SYSTEM_RESERVE5 IS '系统预留5'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.DEL_FLG IS '删除区分||0:有效 1：无效(逻辑删除)'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.SYS_REG_TMSP IS '登录时间'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.SYS_REG_USR_CD IS '登录者'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.SYS_UPD_TMSP IS '更新时间'
;
COMMENT ON COLUMN T_AUTH_ROLE_RESOURCE.SYS_UPD_USR_CD IS '更新者'
;
CREATE TABLE T_SYS_BUSINESS_LOGS
(
    ID                            VARCHAR(32) NOT NULL,
    USER_ID                       VARCHAR(32) NOT NULL,
    MODEL_NAME                    VARCHAR(500) NOT NULL,
    ACTION_TYPE                   VARCHAR(500) NOT NULL,
    OP_TIME                       TIMESTAMP(6) NOT NULL,
    OP_TARGET                     VARCHAR(2000) NOT NULL,
    OP_RESULT                     VARCHAR(500) NOT NULL,
    IP_ADDRESS                    VARCHAR(100) NOT NULL,
    SYSTEM_RESERVE1               VARCHAR(200),
    SYSTEM_RESERVE2               VARCHAR(200),
    SYSTEM_RESERVE3               VARCHAR(200),
    SYSTEM_RESERVE4               VARCHAR(32),
    SYSTEM_RESERVE5               VARCHAR(200),
    DEL_FLG                       VARCHAR(1) NOT NULL,
    SYS_REG_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_REG_USR_CD                VARCHAR(30) NOT NULL,
    SYS_UPD_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_UPD_USR_CD                VARCHAR(30) NOT NULL
)
;
ALTER TABLE T_SYS_BUSINESS_LOGS
    ADD CONSTRAINT PK_T_SYS_BUSINESS_LOGS PRIMARY KEY  (ID)
;
COMMENT ON TABLE T_SYS_BUSINESS_LOGS IS '业务日志'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.ID IS '业务日志ID'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.USER_ID IS '用户ID'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.MODEL_NAME IS '模块名称'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.ACTION_TYPE IS '操作类型'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.OP_TIME IS '操作时间'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.OP_TARGET IS '操作内容'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.OP_RESULT IS '操作结果'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.IP_ADDRESS IS 'IP地址'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.SYSTEM_RESERVE1 IS '系统预留1'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.SYSTEM_RESERVE2 IS '系统预留2'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.SYSTEM_RESERVE3 IS '系统预留3'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.SYSTEM_RESERVE4 IS '系统预留4'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.SYSTEM_RESERVE5 IS '系统预留5'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.DEL_FLG IS '删除区分||0:有效 1：无效(逻辑删除)'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.SYS_REG_TMSP IS '登录时间'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.SYS_REG_USR_CD IS '登录者'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.SYS_UPD_TMSP IS '更新时间'
;
COMMENT ON COLUMN T_SYS_BUSINESS_LOGS.SYS_UPD_USR_CD IS '更新者'
;
CREATE TABLE T_AUTH_USER
(
    ID                            VARCHAR(32) NOT NULL,
    USER_NAME                     VARCHAR(30) NOT NULL,
    USER_PSW                      VARCHAR(32) NOT NULL,
    USER_TYPE                     NUMERIC(4,0) NOT NULL,
    USER_ENABLED                  NUMERIC(4,0) NOT NULL,
    FULL_NAME                     VARCHAR(60) NOT NULL,
    SEX                           NUMERIC(4,0) NOT NULL,
    EMAIL                         VARCHAR(50),
    MOBILE_PHONE                  NUMERIC(11,0) NOT NULL,
    COMMENTS                      VARCHAR(300),
    HEAD_SCULPTURE                VARCHAR(32),
    SYSTEM_RESERVE1               VARCHAR(200),
    SYSTEM_RESERVE2               VARCHAR(200),
    SYSTEM_RESERVE3               VARCHAR(200),
    SYSTEM_RESERVE4               VARCHAR(32),
    SYSTEM_RESERVE5               VARCHAR(200),
    DEL_FLG                       VARCHAR(1) NOT NULL,
    SYS_REG_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_REG_USR_CD                VARCHAR(30) NOT NULL,
    SYS_UPD_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_UPD_USR_CD                VARCHAR(30) NOT NULL
)
;
ALTER TABLE T_AUTH_USER
    ADD CONSTRAINT PK_T_AUTH_USER PRIMARY KEY  (ID)
;
COMMENT ON TABLE T_AUTH_USER IS '用户'
;
COMMENT ON COLUMN T_AUTH_USER.ID IS '用户ID'
;
COMMENT ON COLUMN T_AUTH_USER.USER_NAME IS '用户名'
;
COMMENT ON COLUMN T_AUTH_USER.USER_PSW IS '密码'
;
COMMENT ON COLUMN T_AUTH_USER.USER_TYPE IS '用户类型||共通CODE(800001)'
;
COMMENT ON COLUMN T_AUTH_USER.USER_ENABLED IS '是否有效||共通CODE(900003)'
;
COMMENT ON COLUMN T_AUTH_USER.FULL_NAME IS '姓名'
;
COMMENT ON COLUMN T_AUTH_USER.SEX IS '性别||共通CODE(900002)'
;
COMMENT ON COLUMN T_AUTH_USER.EMAIL IS '邮箱'
;
COMMENT ON COLUMN T_AUTH_USER.MOBILE_PHONE IS '联系方式'
;
COMMENT ON COLUMN T_AUTH_USER.COMMENTS IS '备注'
;
COMMENT ON COLUMN T_AUTH_USER.HEAD_SCULPTURE IS '头像'
;
COMMENT ON COLUMN T_AUTH_USER.SYSTEM_RESERVE1 IS '系统预留1'
;
COMMENT ON COLUMN T_AUTH_USER.SYSTEM_RESERVE2 IS '系统预留2'
;
COMMENT ON COLUMN T_AUTH_USER.SYSTEM_RESERVE3 IS '系统预留3'
;
COMMENT ON COLUMN T_AUTH_USER.SYSTEM_RESERVE4 IS '系统预留4'
;
COMMENT ON COLUMN T_AUTH_USER.SYSTEM_RESERVE5 IS '系统预留5'
;
COMMENT ON COLUMN T_AUTH_USER.DEL_FLG IS '删除区分||0:有效 1：无效(逻辑删除)'
;
COMMENT ON COLUMN T_AUTH_USER.SYS_REG_TMSP IS '登录时间'
;
COMMENT ON COLUMN T_AUTH_USER.SYS_REG_USR_CD IS '登录者'
;
COMMENT ON COLUMN T_AUTH_USER.SYS_UPD_TMSP IS '更新时间'
;
COMMENT ON COLUMN T_AUTH_USER.SYS_UPD_USR_CD IS '更新者'
;
CREATE TABLE T_AUTH_USER_ROLE
(
    ID                            VARCHAR(32) NOT NULL,
    USER_ID                       VARCHAR(32) NOT NULL,
    ROLE_ID                       VARCHAR(32) NOT NULL,
    SYSTEM_RESERVE1               VARCHAR(200),
    SYSTEM_RESERVE2               VARCHAR(200),
    SYSTEM_RESERVE3               VARCHAR(200),
    SYSTEM_RESERVE4               VARCHAR(32),
    SYSTEM_RESERVE5               VARCHAR(200),
    DEL_FLG                       VARCHAR(1) NOT NULL,
    SYS_REG_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_REG_USR_CD                VARCHAR(30) NOT NULL,
    SYS_UPD_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_UPD_USR_CD                VARCHAR(30) NOT NULL
)
;
ALTER TABLE T_AUTH_USER_ROLE
    ADD CONSTRAINT PK_T_AUTH_USER_ROLE PRIMARY KEY  (ID)
;
COMMENT ON TABLE T_AUTH_USER_ROLE IS '用户角色关联'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.ID IS '用户角色关联ID'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.USER_ID IS '用户ID'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.ROLE_ID IS '角色ID'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.SYSTEM_RESERVE1 IS '系统预留1'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.SYSTEM_RESERVE2 IS '系统预留2'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.SYSTEM_RESERVE3 IS '系统预留3'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.SYSTEM_RESERVE4 IS '系统预留4'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.SYSTEM_RESERVE5 IS '系统预留5'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.DEL_FLG IS '删除区分||0:有效 1：无效(逻辑删除)'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.SYS_REG_TMSP IS '登录时间'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.SYS_REG_USR_CD IS '登录者'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.SYS_UPD_TMSP IS '更新时间'
;
COMMENT ON COLUMN T_AUTH_USER_ROLE.SYS_UPD_USR_CD IS '更新者'
;
CREATE TABLE T_AUTH_RESOURCE
(
    ID                            VARCHAR(32) NOT NULL,
    PARENT_ID                     VARCHAR(32) NOT NULL,
    RESOURCE_URL                  VARCHAR(200) NOT NULL,
    RESOURCE_NAME                 VARCHAR(60) NOT NULL,
    RESOURCE_TYPE                 VARCHAR(2) NOT NULL,
    COMMENTS                      VARCHAR(300),
    NAVIGATE_URL                  VARCHAR(200),
    BUSINESS_URL                  VARCHAR(200),
    OTHER_URL                     VARCHAR(200),
    USE_FUNCTION                  VARCHAR(200),
    RESOURCE_IMG                  VARCHAR(32),
    RESOURCE_KEY                  VARCHAR(60),
    SHOW_ORDER                    NUMERIC(4,0),
    ISMENU                        VARCHAR(1),
    SYSTEM_RESERVE1               VARCHAR(200),
    SYSTEM_RESERVE2               VARCHAR(200),
    SYSTEM_RESERVE3               VARCHAR(200),
    SYSTEM_RESERVE4               VARCHAR(32),
    SYSTEM_RESERVE5               VARCHAR(200),
    DEL_FLG                       VARCHAR(1) NOT NULL,
    SYS_REG_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_REG_USR_CD                VARCHAR(30) NOT NULL,
    SYS_UPD_TMSP                  TIMESTAMP(6) NOT NULL,
    SYS_UPD_USR_CD                VARCHAR(30) NOT NULL
)
;
ALTER TABLE T_AUTH_RESOURCE
    ADD CONSTRAINT PK_T_AUTH_RESOURCE PRIMARY KEY  (ID)
;
COMMENT ON TABLE T_AUTH_RESOURCE IS '资源表'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.ID IS '资源节点ID'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.PARENT_ID IS '资源父节点ID'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.RESOURCE_URL IS '资源地址'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.RESOURCE_NAME IS '资源名'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.RESOURCE_TYPE IS '资源类型'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.COMMENTS IS '备注'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.NAVIGATE_URL IS '导航URL'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.BUSINESS_URL IS '业务URL'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.OTHER_URL IS '其他URL'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.USE_FUNCTION IS '调用函数'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.RESOURCE_IMG IS '资源图标'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.RESOURCE_KEY IS '资源值'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SHOW_ORDER IS '显示顺序'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.ISMENU IS '菜单区分'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SYSTEM_RESERVE1 IS '系统预留1'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SYSTEM_RESERVE2 IS '系统预留2'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SYSTEM_RESERVE3 IS '系统预留3'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SYSTEM_RESERVE4 IS '系统预留4'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SYSTEM_RESERVE5 IS '系统预留5'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.DEL_FLG IS '删除区分||0:有效 1：无效(逻辑删除)'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SYS_REG_TMSP IS '登录时间'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SYS_REG_USR_CD IS '登录者'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SYS_UPD_TMSP IS '更新时间'
;
COMMENT ON COLUMN T_AUTH_RESOURCE.SYS_UPD_USR_CD IS '更新者'
;
ALTER TABLE T_AUTH_USER_ROLE
    ADD CONSTRAINT FK_T_BARCH_USER_T_BARCH_USER_R FOREIGN KEY(USER_ID) REFERENCES T_AUTH_USER (ID) ON UPDATE NO ACTION ON DELETE NO ACTION
;
ALTER TABLE T_AUTH_USER_ROLE
    ADD CONSTRAINT FK_T_BARCH_ROLE_T_BARCH_USER_R FOREIGN KEY(ROLE_ID) REFERENCES T_AUTH_ROLE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION
;
ALTER TABLE T_AUTH_ROLE_RESOURCE
    ADD CONSTRAINT FK_T_BARCH_ROLE_T_BARCH_ROLE_R FOREIGN KEY(ROLE_ID) REFERENCES T_AUTH_ROLE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION
;
ALTER TABLE T_AUTH_ROLE_RESOURCE
    ADD CONSTRAINT FK_T_BARCH_RESOURCE_T_BARCH_RO FOREIGN KEY(RESOURCE_ID) REFERENCES T_AUTH_RESOURCE (ID) ON UPDATE NO ACTION ON DELETE NO ACTION
;
