package com.ssmssm.core.entity;



public abstract class BaseCriteria {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_user
     * @mbggenerated
     */
    protected Page page;
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }
}