package com.ssmssm.entity.system;

import java.io.Serializable;

public class BolbFile extends BolbFileKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_blob_file.blob_file_name
     * @mbggenerated
     */
    private String blobFileName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_blob_file.model_name
     * @mbggenerated
     */
    private String modelName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_blob_file.action_type
     * @mbggenerated
     */
    private String actionType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_blob_file
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_blob_file.blob_file_name
     * @return  the value of t_sys_blob_file.blob_file_name
     * @mbggenerated
     */
    public String getBlobFileName() {
        return blobFileName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_blob_file.blob_file_name
     * @param blobFileName  the value for t_sys_blob_file.blob_file_name
     * @mbggenerated
     */
    public void setBlobFileName(String blobFileName) {
        this.blobFileName = blobFileName == null ? null : blobFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_blob_file.model_name
     * @return  the value of t_sys_blob_file.model_name
     * @mbggenerated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_blob_file.model_name
     * @param modelName  the value for t_sys_blob_file.model_name
     * @mbggenerated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_blob_file.action_type
     * @return  the value of t_sys_blob_file.action_type
     * @mbggenerated
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_blob_file.action_type
     * @param actionType  the value for t_sys_blob_file.action_type
     * @mbggenerated
     */
    public void setActionType(String actionType) {
        this.actionType = actionType == null ? null : actionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_blob_file
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", blobFileName=").append(blobFileName);
        sb.append(", modelName=").append(modelName);
        sb.append(", actionType=").append(actionType);
        sb.append("]");
        return sb.toString();
    }
}