package com.ssmssm.entity.system;

import java.io.Serializable;
import java.util.Date;

public class BusinessLogs extends BusinessLogsKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_business_logs.user_id
     * @mbggenerated
     */
    private String userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_business_logs.model_name
     * @mbggenerated
     */
    private String modelName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_business_logs.action_type
     * @mbggenerated
     */
    private String actionType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_business_logs.op_time
     * @mbggenerated
     */
    private Date opTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_business_logs.op_target
     * @mbggenerated
     */
    private String opTarget;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_business_logs.op_result
     * @mbggenerated
     */
    private String opResult;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_business_logs.ip_address
     * @mbggenerated
     */
    private String ipAddress;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_business_logs
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_business_logs.user_id
     * @return  the value of t_sys_business_logs.user_id
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_business_logs.user_id
     * @param userId  the value for t_sys_business_logs.user_id
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_business_logs.model_name
     * @return  the value of t_sys_business_logs.model_name
     * @mbggenerated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_business_logs.model_name
     * @param modelName  the value for t_sys_business_logs.model_name
     * @mbggenerated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_business_logs.action_type
     * @return  the value of t_sys_business_logs.action_type
     * @mbggenerated
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_business_logs.action_type
     * @param actionType  the value for t_sys_business_logs.action_type
     * @mbggenerated
     */
    public void setActionType(String actionType) {
        this.actionType = actionType == null ? null : actionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_business_logs.op_time
     * @return  the value of t_sys_business_logs.op_time
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_business_logs.op_time
     * @param opTime  the value for t_sys_business_logs.op_time
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_business_logs.op_target
     * @return  the value of t_sys_business_logs.op_target
     * @mbggenerated
     */
    public String getOpTarget() {
        return opTarget;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_business_logs.op_target
     * @param opTarget  the value for t_sys_business_logs.op_target
     * @mbggenerated
     */
    public void setOpTarget(String opTarget) {
        this.opTarget = opTarget == null ? null : opTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_business_logs.op_result
     * @return  the value of t_sys_business_logs.op_result
     * @mbggenerated
     */
    public String getOpResult() {
        return opResult;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_business_logs.op_result
     * @param opResult  the value for t_sys_business_logs.op_result
     * @mbggenerated
     */
    public void setOpResult(String opResult) {
        this.opResult = opResult == null ? null : opResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_business_logs.ip_address
     * @return  the value of t_sys_business_logs.ip_address
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_business_logs.ip_address
     * @param ipAddress  the value for t_sys_business_logs.ip_address
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_business_logs
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", modelName=").append(modelName);
        sb.append(", actionType=").append(actionType);
        sb.append(", opTime=").append(opTime);
        sb.append(", opTarget=").append(opTarget);
        sb.append(", opResult=").append(opResult);
        sb.append(", ipAddress=").append(ipAddress);
        sb.append("]");
        return sb.toString();
    }
}