package com.ssmssm.entity.system;

import java.io.Serializable;

public class CommonCode extends CommonCodeKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_common_code.code_id
     * @mbggenerated
     */
    private Integer codeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_common_code.code_dtl_id
     * @mbggenerated
     */
    private Short codeDtlId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_common_code.parent_code_id
     * @mbggenerated
     */
    private Long parentCodeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_sys_common_code.code_dtl_name
     * @mbggenerated
     */
    private String codeDtlName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_common_code.code_id
     * @return  the value of t_sys_common_code.code_id
     * @mbggenerated
     */
    public Integer getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_common_code.code_id
     * @param codeId  the value for t_sys_common_code.code_id
     * @mbggenerated
     */
    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_common_code.code_dtl_id
     * @return  the value of t_sys_common_code.code_dtl_id
     * @mbggenerated
     */
    public Short getCodeDtlId() {
        return codeDtlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_common_code.code_dtl_id
     * @param codeDtlId  the value for t_sys_common_code.code_dtl_id
     * @mbggenerated
     */
    public void setCodeDtlId(Short codeDtlId) {
        this.codeDtlId = codeDtlId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_common_code.parent_code_id
     * @return  the value of t_sys_common_code.parent_code_id
     * @mbggenerated
     */
    public Long getParentCodeId() {
        return parentCodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_common_code.parent_code_id
     * @param parentCodeId  the value for t_sys_common_code.parent_code_id
     * @mbggenerated
     */
    public void setParentCodeId(Long parentCodeId) {
        this.parentCodeId = parentCodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_sys_common_code.code_dtl_name
     * @return  the value of t_sys_common_code.code_dtl_name
     * @mbggenerated
     */
    public String getCodeDtlName() {
        return codeDtlName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_sys_common_code.code_dtl_name
     * @param codeDtlName  the value for t_sys_common_code.code_dtl_name
     * @mbggenerated
     */
    public void setCodeDtlName(String codeDtlName) {
        this.codeDtlName = codeDtlName == null ? null : codeDtlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_common_code
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", codeId=").append(codeId);
        sb.append(", codeDtlId=").append(codeDtlId);
        sb.append(", parentCodeId=").append(parentCodeId);
        sb.append(", codeDtlName=").append(codeDtlName);
        sb.append("]");
        return sb.toString();
    }
}