package com.ssmssm.entity.system;

import java.io.Serializable;

public class Resource extends ResourceKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.parent_id
     * @mbggenerated
     */
    private String parentId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.resource_url
     * @mbggenerated
     */
    private String resourceUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.resource_name
     * @mbggenerated
     */
    private String resourceName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.resource_type
     * @mbggenerated
     */
    private String resourceType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.comments
     * @mbggenerated
     */
    private String comments;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.navigate_url
     * @mbggenerated
     */
    private String navigateUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.business_url
     * @mbggenerated
     */
    private String businessUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.other_url
     * @mbggenerated
     */
    private String otherUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.use_function
     * @mbggenerated
     */
    private String useFunction;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.resource_img
     * @mbggenerated
     */
    private String resourceImg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.resource_key
     * @mbggenerated
     */
    private String resourceKey;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.show_order
     * @mbggenerated
     */
    private Short showOrder;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_resource.ismenu
     * @mbggenerated
     */
    private String ismenu;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.parent_id
     * @return  the value of t_auth_resource.parent_id
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.parent_id
     * @param parentId  the value for t_auth_resource.parent_id
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.resource_url
     * @return  the value of t_auth_resource.resource_url
     * @mbggenerated
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.resource_url
     * @param resourceUrl  the value for t_auth_resource.resource_url
     * @mbggenerated
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.resource_name
     * @return  the value of t_auth_resource.resource_name
     * @mbggenerated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.resource_name
     * @param resourceName  the value for t_auth_resource.resource_name
     * @mbggenerated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.resource_type
     * @return  the value of t_auth_resource.resource_type
     * @mbggenerated
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.resource_type
     * @param resourceType  the value for t_auth_resource.resource_type
     * @mbggenerated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.comments
     * @return  the value of t_auth_resource.comments
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.comments
     * @param comments  the value for t_auth_resource.comments
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.navigate_url
     * @return  the value of t_auth_resource.navigate_url
     * @mbggenerated
     */
    public String getNavigateUrl() {
        return navigateUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.navigate_url
     * @param navigateUrl  the value for t_auth_resource.navigate_url
     * @mbggenerated
     */
    public void setNavigateUrl(String navigateUrl) {
        this.navigateUrl = navigateUrl == null ? null : navigateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.business_url
     * @return  the value of t_auth_resource.business_url
     * @mbggenerated
     */
    public String getBusinessUrl() {
        return businessUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.business_url
     * @param businessUrl  the value for t_auth_resource.business_url
     * @mbggenerated
     */
    public void setBusinessUrl(String businessUrl) {
        this.businessUrl = businessUrl == null ? null : businessUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.other_url
     * @return  the value of t_auth_resource.other_url
     * @mbggenerated
     */
    public String getOtherUrl() {
        return otherUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.other_url
     * @param otherUrl  the value for t_auth_resource.other_url
     * @mbggenerated
     */
    public void setOtherUrl(String otherUrl) {
        this.otherUrl = otherUrl == null ? null : otherUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.use_function
     * @return  the value of t_auth_resource.use_function
     * @mbggenerated
     */
    public String getUseFunction() {
        return useFunction;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.use_function
     * @param useFunction  the value for t_auth_resource.use_function
     * @mbggenerated
     */
    public void setUseFunction(String useFunction) {
        this.useFunction = useFunction == null ? null : useFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.resource_img
     * @return  the value of t_auth_resource.resource_img
     * @mbggenerated
     */
    public String getResourceImg() {
        return resourceImg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.resource_img
     * @param resourceImg  the value for t_auth_resource.resource_img
     * @mbggenerated
     */
    public void setResourceImg(String resourceImg) {
        this.resourceImg = resourceImg == null ? null : resourceImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.resource_key
     * @return  the value of t_auth_resource.resource_key
     * @mbggenerated
     */
    public String getResourceKey() {
        return resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.resource_key
     * @param resourceKey  the value for t_auth_resource.resource_key
     * @mbggenerated
     */
    public void setResourceKey(String resourceKey) {
        this.resourceKey = resourceKey == null ? null : resourceKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.show_order
     * @return  the value of t_auth_resource.show_order
     * @mbggenerated
     */
    public Short getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.show_order
     * @param showOrder  the value for t_auth_resource.show_order
     * @mbggenerated
     */
    public void setShowOrder(Short showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_resource.ismenu
     * @return  the value of t_auth_resource.ismenu
     * @mbggenerated
     */
    public String getIsmenu() {
        return ismenu;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_resource.ismenu
     * @param ismenu  the value for t_auth_resource.ismenu
     * @mbggenerated
     */
    public void setIsmenu(String ismenu) {
        this.ismenu = ismenu == null ? null : ismenu.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", parentId=").append(parentId);
        sb.append(", resourceUrl=").append(resourceUrl);
        sb.append(", resourceName=").append(resourceName);
        sb.append(", resourceType=").append(resourceType);
        sb.append(", comments=").append(comments);
        sb.append(", navigateUrl=").append(navigateUrl);
        sb.append(", businessUrl=").append(businessUrl);
        sb.append(", otherUrl=").append(otherUrl);
        sb.append(", useFunction=").append(useFunction);
        sb.append(", resourceImg=").append(resourceImg);
        sb.append(", resourceKey=").append(resourceKey);
        sb.append(", showOrder=").append(showOrder);
        sb.append(", ismenu=").append(ismenu);
        sb.append("]");
        return sb.toString();
    }
}