package com.ssmssm.entity.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.ssmssm.core.entity.BaseCriteria;
import com.ssmssm.core.entity.Page;

public class ResourceCriteria extends BaseCriteria {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public ResourceCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;
        
        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }
        
        public boolean isValid() {
            return criteria.size() > 0;
        }
        
        public List<Criterion> getAllCriteria() {
            return criteria;
        }
        
        public List<Criterion> getCriteria() {
            return criteria;
        }
        
        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }
        
        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }
        
        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }
        
        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria)this;
        }
        
        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria)this;
        }
        
        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria)this;
        }
        
        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria)this;
        }
        
        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria)this;
        }
        
        public Criteria andParentIdEqualTo(String value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdLessThan(String value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdLike(String value) {
            addCriterion("parent_id like", value, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdNotLike(String value) {
            addCriterion("parent_id not like", value, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdIn(List<String> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlIsNull() {
            addCriterion("resource_url is null");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlIsNotNull() {
            addCriterion("resource_url is not null");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlEqualTo(String value) {
            addCriterion("resource_url =", value, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlNotEqualTo(String value) {
            addCriterion("resource_url <>", value, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlGreaterThan(String value) {
            addCriterion("resource_url >", value, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlGreaterThanOrEqualTo(String value) {
            addCriterion("resource_url >=", value, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlLessThan(String value) {
            addCriterion("resource_url <", value, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlLessThanOrEqualTo(String value) {
            addCriterion("resource_url <=", value, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlLike(String value) {
            addCriterion("resource_url like", value, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlNotLike(String value) {
            addCriterion("resource_url not like", value, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlIn(List<String> values) {
            addCriterion("resource_url in", values, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlNotIn(List<String> values) {
            addCriterion("resource_url not in", values, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlBetween(String value1, String value2) {
            addCriterion("resource_url between", value1, value2, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceUrlNotBetween(String value1, String value2) {
            addCriterion("resource_url not between", value1, value2, "resourceUrl");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameIsNull() {
            addCriterion("resource_name is null");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameIsNotNull() {
            addCriterion("resource_name is not null");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameEqualTo(String value) {
            addCriterion("resource_name =", value, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameNotEqualTo(String value) {
            addCriterion("resource_name <>", value, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameGreaterThan(String value) {
            addCriterion("resource_name >", value, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("resource_name >=", value, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameLessThan(String value) {
            addCriterion("resource_name <", value, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameLessThanOrEqualTo(String value) {
            addCriterion("resource_name <=", value, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameLike(String value) {
            addCriterion("resource_name like", value, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameNotLike(String value) {
            addCriterion("resource_name not like", value, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameIn(List<String> values) {
            addCriterion("resource_name in", values, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameNotIn(List<String> values) {
            addCriterion("resource_name not in", values, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameBetween(String value1, String value2) {
            addCriterion("resource_name between", value1, value2, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceNameNotBetween(String value1, String value2) {
            addCriterion("resource_name not between", value1, value2, "resourceName");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeIsNull() {
            addCriterion("resource_type is null");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeIsNotNull() {
            addCriterion("resource_type is not null");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeEqualTo(String value) {
            addCriterion("resource_type =", value, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeNotEqualTo(String value) {
            addCriterion("resource_type <>", value, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeGreaterThan(String value) {
            addCriterion("resource_type >", value, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("resource_type >=", value, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeLessThan(String value) {
            addCriterion("resource_type <", value, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeLessThanOrEqualTo(String value) {
            addCriterion("resource_type <=", value, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeLike(String value) {
            addCriterion("resource_type like", value, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeNotLike(String value) {
            addCriterion("resource_type not like", value, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeIn(List<String> values) {
            addCriterion("resource_type in", values, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeNotIn(List<String> values) {
            addCriterion("resource_type not in", values, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeBetween(String value1, String value2) {
            addCriterion("resource_type between", value1, value2, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andResourceTypeNotBetween(String value1, String value2) {
            addCriterion("resource_type not between", value1, value2, "resourceType");
            return (Criteria)this;
        }
        
        public Criteria andCommentsIsNull() {
            addCriterion("comments is null");
            return (Criteria)this;
        }
        
        public Criteria andCommentsIsNotNull() {
            addCriterion("comments is not null");
            return (Criteria)this;
        }
        
        public Criteria andCommentsEqualTo(String value) {
            addCriterion("comments =", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("comments <>", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("comments >", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("comments >=", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsLessThan(String value) {
            addCriterion("comments <", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("comments <=", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsLike(String value) {
            addCriterion("comments like", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsNotLike(String value) {
            addCriterion("comments not like", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsIn(List<String> values) {
            addCriterion("comments in", values, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("comments not in", values, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("comments between", value1, value2, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("comments not between", value1, value2, "comments");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlIsNull() {
            addCriterion("navigate_url is null");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlIsNotNull() {
            addCriterion("navigate_url is not null");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlEqualTo(String value) {
            addCriterion("navigate_url =", value, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlNotEqualTo(String value) {
            addCriterion("navigate_url <>", value, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlGreaterThan(String value) {
            addCriterion("navigate_url >", value, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlGreaterThanOrEqualTo(String value) {
            addCriterion("navigate_url >=", value, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlLessThan(String value) {
            addCriterion("navigate_url <", value, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlLessThanOrEqualTo(String value) {
            addCriterion("navigate_url <=", value, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlLike(String value) {
            addCriterion("navigate_url like", value, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlNotLike(String value) {
            addCriterion("navigate_url not like", value, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlIn(List<String> values) {
            addCriterion("navigate_url in", values, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlNotIn(List<String> values) {
            addCriterion("navigate_url not in", values, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlBetween(String value1, String value2) {
            addCriterion("navigate_url between", value1, value2, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andNavigateUrlNotBetween(String value1, String value2) {
            addCriterion("navigate_url not between", value1, value2, "navigateUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlIsNull() {
            addCriterion("business_url is null");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlIsNotNull() {
            addCriterion("business_url is not null");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlEqualTo(String value) {
            addCriterion("business_url =", value, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlNotEqualTo(String value) {
            addCriterion("business_url <>", value, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlGreaterThan(String value) {
            addCriterion("business_url >", value, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlGreaterThanOrEqualTo(String value) {
            addCriterion("business_url >=", value, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlLessThan(String value) {
            addCriterion("business_url <", value, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlLessThanOrEqualTo(String value) {
            addCriterion("business_url <=", value, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlLike(String value) {
            addCriterion("business_url like", value, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlNotLike(String value) {
            addCriterion("business_url not like", value, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlIn(List<String> values) {
            addCriterion("business_url in", values, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlNotIn(List<String> values) {
            addCriterion("business_url not in", values, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlBetween(String value1, String value2) {
            addCriterion("business_url between", value1, value2, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andBusinessUrlNotBetween(String value1, String value2) {
            addCriterion("business_url not between", value1, value2, "businessUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlIsNull() {
            addCriterion("other_url is null");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlIsNotNull() {
            addCriterion("other_url is not null");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlEqualTo(String value) {
            addCriterion("other_url =", value, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlNotEqualTo(String value) {
            addCriterion("other_url <>", value, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlGreaterThan(String value) {
            addCriterion("other_url >", value, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlGreaterThanOrEqualTo(String value) {
            addCriterion("other_url >=", value, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlLessThan(String value) {
            addCriterion("other_url <", value, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlLessThanOrEqualTo(String value) {
            addCriterion("other_url <=", value, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlLike(String value) {
            addCriterion("other_url like", value, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlNotLike(String value) {
            addCriterion("other_url not like", value, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlIn(List<String> values) {
            addCriterion("other_url in", values, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlNotIn(List<String> values) {
            addCriterion("other_url not in", values, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlBetween(String value1, String value2) {
            addCriterion("other_url between", value1, value2, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andOtherUrlNotBetween(String value1, String value2) {
            addCriterion("other_url not between", value1, value2, "otherUrl");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionIsNull() {
            addCriterion("use_function is null");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionIsNotNull() {
            addCriterion("use_function is not null");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionEqualTo(String value) {
            addCriterion("use_function =", value, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionNotEqualTo(String value) {
            addCriterion("use_function <>", value, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionGreaterThan(String value) {
            addCriterion("use_function >", value, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionGreaterThanOrEqualTo(String value) {
            addCriterion("use_function >=", value, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionLessThan(String value) {
            addCriterion("use_function <", value, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionLessThanOrEqualTo(String value) {
            addCriterion("use_function <=", value, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionLike(String value) {
            addCriterion("use_function like", value, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionNotLike(String value) {
            addCriterion("use_function not like", value, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionIn(List<String> values) {
            addCriterion("use_function in", values, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionNotIn(List<String> values) {
            addCriterion("use_function not in", values, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionBetween(String value1, String value2) {
            addCriterion("use_function between", value1, value2, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andUseFunctionNotBetween(String value1, String value2) {
            addCriterion("use_function not between", value1, value2, "useFunction");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgIsNull() {
            addCriterion("resource_img is null");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgIsNotNull() {
            addCriterion("resource_img is not null");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgEqualTo(String value) {
            addCriterion("resource_img =", value, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgNotEqualTo(String value) {
            addCriterion("resource_img <>", value, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgGreaterThan(String value) {
            addCriterion("resource_img >", value, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgGreaterThanOrEqualTo(String value) {
            addCriterion("resource_img >=", value, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgLessThan(String value) {
            addCriterion("resource_img <", value, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgLessThanOrEqualTo(String value) {
            addCriterion("resource_img <=", value, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgLike(String value) {
            addCriterion("resource_img like", value, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgNotLike(String value) {
            addCriterion("resource_img not like", value, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgIn(List<String> values) {
            addCriterion("resource_img in", values, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgNotIn(List<String> values) {
            addCriterion("resource_img not in", values, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgBetween(String value1, String value2) {
            addCriterion("resource_img between", value1, value2, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceImgNotBetween(String value1, String value2) {
            addCriterion("resource_img not between", value1, value2, "resourceImg");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyIsNull() {
            addCriterion("resource_key is null");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyIsNotNull() {
            addCriterion("resource_key is not null");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyEqualTo(String value) {
            addCriterion("resource_key =", value, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyNotEqualTo(String value) {
            addCriterion("resource_key <>", value, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyGreaterThan(String value) {
            addCriterion("resource_key >", value, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyGreaterThanOrEqualTo(String value) {
            addCriterion("resource_key >=", value, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyLessThan(String value) {
            addCriterion("resource_key <", value, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyLessThanOrEqualTo(String value) {
            addCriterion("resource_key <=", value, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyLike(String value) {
            addCriterion("resource_key like", value, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyNotLike(String value) {
            addCriterion("resource_key not like", value, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyIn(List<String> values) {
            addCriterion("resource_key in", values, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyNotIn(List<String> values) {
            addCriterion("resource_key not in", values, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyBetween(String value1, String value2) {
            addCriterion("resource_key between", value1, value2, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andResourceKeyNotBetween(String value1, String value2) {
            addCriterion("resource_key not between", value1, value2, "resourceKey");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderIsNull() {
            addCriterion("show_order is null");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderIsNotNull() {
            addCriterion("show_order is not null");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderEqualTo(Short value) {
            addCriterion("show_order =", value, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderNotEqualTo(Short value) {
            addCriterion("show_order <>", value, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderGreaterThan(Short value) {
            addCriterion("show_order >", value, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderGreaterThanOrEqualTo(Short value) {
            addCriterion("show_order >=", value, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderLessThan(Short value) {
            addCriterion("show_order <", value, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderLessThanOrEqualTo(Short value) {
            addCriterion("show_order <=", value, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderIn(List<Short> values) {
            addCriterion("show_order in", values, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderNotIn(List<Short> values) {
            addCriterion("show_order not in", values, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderBetween(Short value1, Short value2) {
            addCriterion("show_order between", value1, value2, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andShowOrderNotBetween(Short value1, Short value2) {
            addCriterion("show_order not between", value1, value2, "showOrder");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuIsNull() {
            addCriterion("ismenu is null");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuIsNotNull() {
            addCriterion("ismenu is not null");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuEqualTo(String value) {
            addCriterion("ismenu =", value, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuNotEqualTo(String value) {
            addCriterion("ismenu <>", value, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuGreaterThan(String value) {
            addCriterion("ismenu >", value, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuGreaterThanOrEqualTo(String value) {
            addCriterion("ismenu >=", value, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuLessThan(String value) {
            addCriterion("ismenu <", value, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuLessThanOrEqualTo(String value) {
            addCriterion("ismenu <=", value, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuLike(String value) {
            addCriterion("ismenu like", value, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuNotLike(String value) {
            addCriterion("ismenu not like", value, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuIn(List<String> values) {
            addCriterion("ismenu in", values, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuNotIn(List<String> values) {
            addCriterion("ismenu not in", values, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuBetween(String value1, String value2) {
            addCriterion("ismenu between", value1, value2, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andIsmenuNotBetween(String value1, String value2) {
            addCriterion("ismenu not between", value1, value2, "ismenu");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1IsNull() {
            addCriterion("system_reserve1 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1IsNotNull() {
            addCriterion("system_reserve1 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1EqualTo(String value) {
            addCriterion("system_reserve1 =", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotEqualTo(String value) {
            addCriterion("system_reserve1 <>", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1GreaterThan(String value) {
            addCriterion("system_reserve1 >", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve1 >=", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1LessThan(String value) {
            addCriterion("system_reserve1 <", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1LessThanOrEqualTo(String value) {
            addCriterion("system_reserve1 <=", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1Like(String value) {
            addCriterion("system_reserve1 like", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotLike(String value) {
            addCriterion("system_reserve1 not like", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1In(List<String> values) {
            addCriterion("system_reserve1 in", values, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotIn(List<String> values) {
            addCriterion("system_reserve1 not in", values, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1Between(String value1, String value2) {
            addCriterion("system_reserve1 between", value1, value2, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotBetween(String value1, String value2) {
            addCriterion("system_reserve1 not between", value1, value2, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2IsNull() {
            addCriterion("system_reserve2 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2IsNotNull() {
            addCriterion("system_reserve2 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2EqualTo(String value) {
            addCriterion("system_reserve2 =", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotEqualTo(String value) {
            addCriterion("system_reserve2 <>", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2GreaterThan(String value) {
            addCriterion("system_reserve2 >", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve2 >=", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2LessThan(String value) {
            addCriterion("system_reserve2 <", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2LessThanOrEqualTo(String value) {
            addCriterion("system_reserve2 <=", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2Like(String value) {
            addCriterion("system_reserve2 like", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotLike(String value) {
            addCriterion("system_reserve2 not like", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2In(List<String> values) {
            addCriterion("system_reserve2 in", values, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotIn(List<String> values) {
            addCriterion("system_reserve2 not in", values, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2Between(String value1, String value2) {
            addCriterion("system_reserve2 between", value1, value2, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotBetween(String value1, String value2) {
            addCriterion("system_reserve2 not between", value1, value2, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3IsNull() {
            addCriterion("system_reserve3 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3IsNotNull() {
            addCriterion("system_reserve3 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3EqualTo(String value) {
            addCriterion("system_reserve3 =", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotEqualTo(String value) {
            addCriterion("system_reserve3 <>", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3GreaterThan(String value) {
            addCriterion("system_reserve3 >", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve3 >=", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3LessThan(String value) {
            addCriterion("system_reserve3 <", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3LessThanOrEqualTo(String value) {
            addCriterion("system_reserve3 <=", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3Like(String value) {
            addCriterion("system_reserve3 like", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotLike(String value) {
            addCriterion("system_reserve3 not like", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3In(List<String> values) {
            addCriterion("system_reserve3 in", values, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotIn(List<String> values) {
            addCriterion("system_reserve3 not in", values, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3Between(String value1, String value2) {
            addCriterion("system_reserve3 between", value1, value2, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotBetween(String value1, String value2) {
            addCriterion("system_reserve3 not between", value1, value2, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4IsNull() {
            addCriterion("system_reserve4 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4IsNotNull() {
            addCriterion("system_reserve4 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4EqualTo(String value) {
            addCriterion("system_reserve4 =", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotEqualTo(String value) {
            addCriterion("system_reserve4 <>", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4GreaterThan(String value) {
            addCriterion("system_reserve4 >", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve4 >=", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4LessThan(String value) {
            addCriterion("system_reserve4 <", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4LessThanOrEqualTo(String value) {
            addCriterion("system_reserve4 <=", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4Like(String value) {
            addCriterion("system_reserve4 like", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotLike(String value) {
            addCriterion("system_reserve4 not like", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4In(List<String> values) {
            addCriterion("system_reserve4 in", values, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotIn(List<String> values) {
            addCriterion("system_reserve4 not in", values, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4Between(String value1, String value2) {
            addCriterion("system_reserve4 between", value1, value2, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotBetween(String value1, String value2) {
            addCriterion("system_reserve4 not between", value1, value2, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5IsNull() {
            addCriterion("system_reserve5 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5IsNotNull() {
            addCriterion("system_reserve5 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5EqualTo(String value) {
            addCriterion("system_reserve5 =", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotEqualTo(String value) {
            addCriterion("system_reserve5 <>", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5GreaterThan(String value) {
            addCriterion("system_reserve5 >", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve5 >=", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5LessThan(String value) {
            addCriterion("system_reserve5 <", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5LessThanOrEqualTo(String value) {
            addCriterion("system_reserve5 <=", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5Like(String value) {
            addCriterion("system_reserve5 like", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotLike(String value) {
            addCriterion("system_reserve5 not like", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5In(List<String> values) {
            addCriterion("system_reserve5 in", values, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotIn(List<String> values) {
            addCriterion("system_reserve5 not in", values, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5Between(String value1, String value2) {
            addCriterion("system_reserve5 between", value1, value2, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotBetween(String value1, String value2) {
            addCriterion("system_reserve5 not between", value1, value2, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgIsNull() {
            addCriterion("del_flg is null");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgIsNotNull() {
            addCriterion("del_flg is not null");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgEqualTo(String value) {
            addCriterion("del_flg =", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotEqualTo(String value) {
            addCriterion("del_flg <>", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgGreaterThan(String value) {
            addCriterion("del_flg >", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("del_flg >=", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgLessThan(String value) {
            addCriterion("del_flg <", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgLessThanOrEqualTo(String value) {
            addCriterion("del_flg <=", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgLike(String value) {
            addCriterion("del_flg like", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotLike(String value) {
            addCriterion("del_flg not like", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgIn(List<String> values) {
            addCriterion("del_flg in", values, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotIn(List<String> values) {
            addCriterion("del_flg not in", values, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgBetween(String value1, String value2) {
            addCriterion("del_flg between", value1, value2, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotBetween(String value1, String value2) {
            addCriterion("del_flg not between", value1, value2, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspIsNull() {
            addCriterion("sys_reg_tmsp is null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspIsNotNull() {
            addCriterion("sys_reg_tmsp is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspEqualTo(Date value) {
            addCriterion("sys_reg_tmsp =", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspNotEqualTo(Date value) {
            addCriterion("sys_reg_tmsp <>", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspGreaterThan(Date value) {
            addCriterion("sys_reg_tmsp >", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_reg_tmsp >=", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspLessThan(Date value) {
            addCriterion("sys_reg_tmsp <", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspLessThanOrEqualTo(Date value) {
            addCriterion("sys_reg_tmsp <=", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspIn(List<Date> values) {
            addCriterion("sys_reg_tmsp in", values, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspNotIn(List<Date> values) {
            addCriterion("sys_reg_tmsp not in", values, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspBetween(Date value1, Date value2) {
            addCriterion("sys_reg_tmsp between", value1, value2, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspNotBetween(Date value1, Date value2) {
            addCriterion("sys_reg_tmsp not between", value1, value2, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdIsNull() {
            addCriterion("sys_reg_usr_cd is null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdIsNotNull() {
            addCriterion("sys_reg_usr_cd is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdEqualTo(String value) {
            addCriterion("sys_reg_usr_cd =", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotEqualTo(String value) {
            addCriterion("sys_reg_usr_cd <>", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdGreaterThan(String value) {
            addCriterion("sys_reg_usr_cd >", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_reg_usr_cd >=", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdLessThan(String value) {
            addCriterion("sys_reg_usr_cd <", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdLessThanOrEqualTo(String value) {
            addCriterion("sys_reg_usr_cd <=", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdLike(String value) {
            addCriterion("sys_reg_usr_cd like", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotLike(String value) {
            addCriterion("sys_reg_usr_cd not like", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdIn(List<String> values) {
            addCriterion("sys_reg_usr_cd in", values, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotIn(List<String> values) {
            addCriterion("sys_reg_usr_cd not in", values, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdBetween(String value1, String value2) {
            addCriterion("sys_reg_usr_cd between", value1, value2, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotBetween(String value1, String value2) {
            addCriterion("sys_reg_usr_cd not between", value1, value2, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspIsNull() {
            addCriterion("sys_upd_tmsp is null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspIsNotNull() {
            addCriterion("sys_upd_tmsp is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspEqualTo(Date value) {
            addCriterion("sys_upd_tmsp =", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspNotEqualTo(Date value) {
            addCriterion("sys_upd_tmsp <>", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspGreaterThan(Date value) {
            addCriterion("sys_upd_tmsp >", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_upd_tmsp >=", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspLessThan(Date value) {
            addCriterion("sys_upd_tmsp <", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspLessThanOrEqualTo(Date value) {
            addCriterion("sys_upd_tmsp <=", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspIn(List<Date> values) {
            addCriterion("sys_upd_tmsp in", values, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspNotIn(List<Date> values) {
            addCriterion("sys_upd_tmsp not in", values, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspBetween(Date value1, Date value2) {
            addCriterion("sys_upd_tmsp between", value1, value2, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspNotBetween(Date value1, Date value2) {
            addCriterion("sys_upd_tmsp not between", value1, value2, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdIsNull() {
            addCriterion("sys_upd_usr_cd is null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdIsNotNull() {
            addCriterion("sys_upd_usr_cd is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdEqualTo(String value) {
            addCriterion("sys_upd_usr_cd =", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotEqualTo(String value) {
            addCriterion("sys_upd_usr_cd <>", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdGreaterThan(String value) {
            addCriterion("sys_upd_usr_cd >", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_upd_usr_cd >=", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdLessThan(String value) {
            addCriterion("sys_upd_usr_cd <", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdLessThanOrEqualTo(String value) {
            addCriterion("sys_upd_usr_cd <=", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdLike(String value) {
            addCriterion("sys_upd_usr_cd like", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotLike(String value) {
            addCriterion("sys_upd_usr_cd not like", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdIn(List<String> values) {
            addCriterion("sys_upd_usr_cd in", values, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotIn(List<String> values) {
            addCriterion("sys_upd_usr_cd not in", values, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdBetween(String value1, String value2) {
            addCriterion("sys_upd_usr_cd between", value1, value2, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotBetween(String value1, String value2) {
            addCriterion("sys_upd_usr_cd not between", value1, value2, "sysUpdUsrCd");
            return (Criteria)this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_auth_resource
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;
        
        private Object value;
        
        private Object secondValue;
        
        private boolean noValue;
        
        private boolean singleValue;
        
        private boolean betweenValue;
        
        private boolean listValue;
        
        private String typeHandler;
        
        public String getCondition() {
            return condition;
        }
        
        public Object getValue() {
            return value;
        }
        
        public Object getSecondValue() {
            return secondValue;
        }
        
        public boolean isNoValue() {
            return noValue;
        }
        
        public boolean isSingleValue() {
            return singleValue;
        }
        
        public boolean isBetweenValue() {
            return betweenValue;
        }
        
        public boolean isListValue() {
            return listValue;
        }
        
        public String getTypeHandler() {
            return typeHandler;
        }
        
        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }
        
        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            }
            else {
                this.singleValue = true;
            }
        }
        
        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }
        
        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }
        
        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_AUTH_RESOURCE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(\"ID\") like", value.toUpperCase(), "id");
            return this;
        }

        public Criteria andParentIdLikeInsensitive(String value) {
            addCriterion("upper(\"PARENT_ID\") like", value.toUpperCase(), "parentId");
            return this;
        }

        public Criteria andResourceUrlLikeInsensitive(String value) {
            addCriterion("upper(\"RESOURCE_URL\") like", value.toUpperCase(), "resourceUrl");
            return this;
        }

        public Criteria andResourceNameLikeInsensitive(String value) {
            addCriterion("upper(\"RESOURCE_NAME\") like", value.toUpperCase(), "resourceName");
            return this;
        }

        public Criteria andResourceTypeLikeInsensitive(String value) {
            addCriterion("upper(\"RESOURCE_TYPE\") like", value.toUpperCase(), "resourceType");
            return this;
        }

        public Criteria andCommentsLikeInsensitive(String value) {
            addCriterion("upper(\"COMMENTS\") like", value.toUpperCase(), "comments");
            return this;
        }

        public Criteria andNavigateUrlLikeInsensitive(String value) {
            addCriterion("upper(\"NAVIGATE_URL\") like", value.toUpperCase(), "navigateUrl");
            return this;
        }

        public Criteria andBusinessUrlLikeInsensitive(String value) {
            addCriterion("upper(\"BUSINESS_URL\") like", value.toUpperCase(), "businessUrl");
            return this;
        }

        public Criteria andOtherUrlLikeInsensitive(String value) {
            addCriterion("upper(\"OTHER_URL\") like", value.toUpperCase(), "otherUrl");
            return this;
        }

        public Criteria andUseFunctionLikeInsensitive(String value) {
            addCriterion("upper(\"USE_FUNCTION\") like", value.toUpperCase(), "useFunction");
            return this;
        }

        public Criteria andResourceImgLikeInsensitive(String value) {
            addCriterion("upper(\"RESOURCE_IMG\") like", value.toUpperCase(), "resourceImg");
            return this;
        }

        public Criteria andResourceKeyLikeInsensitive(String value) {
            addCriterion("upper(\"RESOURCE_KEY\") like", value.toUpperCase(), "resourceKey");
            return this;
        }

        public Criteria andIsmenuLikeInsensitive(String value) {
            addCriterion("upper(\"ISMENU\") like", value.toUpperCase(), "ismenu");
            return this;
        }

        public Criteria andSystemReserve1LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE1\") like", value.toUpperCase(), "systemReserve1");
            return this;
        }

        public Criteria andSystemReserve2LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE2\") like", value.toUpperCase(), "systemReserve2");
            return this;
        }

        public Criteria andSystemReserve3LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE3\") like", value.toUpperCase(), "systemReserve3");
            return this;
        }

        public Criteria andSystemReserve4LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE4\") like", value.toUpperCase(), "systemReserve4");
            return this;
        }

        public Criteria andSystemReserve5LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE5\") like", value.toUpperCase(), "systemReserve5");
            return this;
        }

        public Criteria andDelFlgLikeInsensitive(String value) {
            addCriterion("upper(\"DEL_FLG\") like", value.toUpperCase(), "delFlg");
            return this;
        }

        public Criteria andSysRegUsrCdLikeInsensitive(String value) {
            addCriterion("upper(\"SYS_REG_USR_CD\") like", value.toUpperCase(), "sysRegUsrCd");
            return this;
        }

        public Criteria andSysUpdUsrCdLikeInsensitive(String value) {
            addCriterion("upper(\"SYS_UPD_USR_CD\") like", value.toUpperCase(), "sysUpdUsrCd");
            return this;
        }
    }
}