package com.ssmssm.entity.system;

import java.io.Serializable;

public class RoleResource extends RoleResourceKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_role_resource.role_id
     * @mbggenerated
     */
    private String roleId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_auth_role_resource.resource_id
     * @mbggenerated
     */
    private String resourceId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_role_resource.role_id
     * @return  the value of t_auth_role_resource.role_id
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_role_resource.role_id
     * @param roleId  the value for t_auth_role_resource.role_id
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_auth_role_resource.resource_id
     * @return  the value of t_auth_role_resource.resource_id
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_auth_role_resource.resource_id
     * @param resourceId  the value for t_auth_role_resource.resource_id
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_role_resource
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", resourceId=").append(resourceId);
        sb.append("]");
        return sb.toString();
    }
}