package com.ssmssm.entity.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.ssmssm.core.entity.BaseCriteria;
import com.ssmssm.core.entity.Page;

public class UserRoleCriteria extends BaseCriteria {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public UserRoleCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;
        
        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }
        
        public boolean isValid() {
            return criteria.size() > 0;
        }
        
        public List<Criterion> getAllCriteria() {
            return criteria;
        }
        
        public List<Criterion> getCriteria() {
            return criteria;
        }
        
        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }
        
        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }
        
        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }
        
        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria)this;
        }
        
        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria)this;
        }
        
        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria)this;
        }
        
        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria)this;
        }
        
        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria)this;
        }
        
        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria)this;
        }
        
        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdEqualTo(String value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdNotEqualTo(String value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdGreaterThan(String value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdLessThan(String value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdLessThanOrEqualTo(String value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdLike(String value) {
            addCriterion("role_id like", value, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdNotLike(String value) {
            addCriterion("role_id not like", value, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdIn(List<String> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdNotIn(List<String> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdBetween(String value1, String value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andRoleIdNotBetween(String value1, String value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1IsNull() {
            addCriterion("system_reserve1 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1IsNotNull() {
            addCriterion("system_reserve1 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1EqualTo(String value) {
            addCriterion("system_reserve1 =", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotEqualTo(String value) {
            addCriterion("system_reserve1 <>", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1GreaterThan(String value) {
            addCriterion("system_reserve1 >", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve1 >=", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1LessThan(String value) {
            addCriterion("system_reserve1 <", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1LessThanOrEqualTo(String value) {
            addCriterion("system_reserve1 <=", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1Like(String value) {
            addCriterion("system_reserve1 like", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotLike(String value) {
            addCriterion("system_reserve1 not like", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1In(List<String> values) {
            addCriterion("system_reserve1 in", values, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotIn(List<String> values) {
            addCriterion("system_reserve1 not in", values, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1Between(String value1, String value2) {
            addCriterion("system_reserve1 between", value1, value2, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotBetween(String value1, String value2) {
            addCriterion("system_reserve1 not between", value1, value2, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2IsNull() {
            addCriterion("system_reserve2 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2IsNotNull() {
            addCriterion("system_reserve2 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2EqualTo(String value) {
            addCriterion("system_reserve2 =", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotEqualTo(String value) {
            addCriterion("system_reserve2 <>", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2GreaterThan(String value) {
            addCriterion("system_reserve2 >", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve2 >=", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2LessThan(String value) {
            addCriterion("system_reserve2 <", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2LessThanOrEqualTo(String value) {
            addCriterion("system_reserve2 <=", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2Like(String value) {
            addCriterion("system_reserve2 like", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotLike(String value) {
            addCriterion("system_reserve2 not like", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2In(List<String> values) {
            addCriterion("system_reserve2 in", values, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotIn(List<String> values) {
            addCriterion("system_reserve2 not in", values, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2Between(String value1, String value2) {
            addCriterion("system_reserve2 between", value1, value2, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotBetween(String value1, String value2) {
            addCriterion("system_reserve2 not between", value1, value2, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3IsNull() {
            addCriterion("system_reserve3 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3IsNotNull() {
            addCriterion("system_reserve3 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3EqualTo(String value) {
            addCriterion("system_reserve3 =", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotEqualTo(String value) {
            addCriterion("system_reserve3 <>", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3GreaterThan(String value) {
            addCriterion("system_reserve3 >", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve3 >=", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3LessThan(String value) {
            addCriterion("system_reserve3 <", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3LessThanOrEqualTo(String value) {
            addCriterion("system_reserve3 <=", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3Like(String value) {
            addCriterion("system_reserve3 like", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotLike(String value) {
            addCriterion("system_reserve3 not like", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3In(List<String> values) {
            addCriterion("system_reserve3 in", values, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotIn(List<String> values) {
            addCriterion("system_reserve3 not in", values, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3Between(String value1, String value2) {
            addCriterion("system_reserve3 between", value1, value2, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotBetween(String value1, String value2) {
            addCriterion("system_reserve3 not between", value1, value2, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4IsNull() {
            addCriterion("system_reserve4 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4IsNotNull() {
            addCriterion("system_reserve4 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4EqualTo(String value) {
            addCriterion("system_reserve4 =", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotEqualTo(String value) {
            addCriterion("system_reserve4 <>", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4GreaterThan(String value) {
            addCriterion("system_reserve4 >", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve4 >=", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4LessThan(String value) {
            addCriterion("system_reserve4 <", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4LessThanOrEqualTo(String value) {
            addCriterion("system_reserve4 <=", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4Like(String value) {
            addCriterion("system_reserve4 like", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotLike(String value) {
            addCriterion("system_reserve4 not like", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4In(List<String> values) {
            addCriterion("system_reserve4 in", values, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotIn(List<String> values) {
            addCriterion("system_reserve4 not in", values, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4Between(String value1, String value2) {
            addCriterion("system_reserve4 between", value1, value2, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotBetween(String value1, String value2) {
            addCriterion("system_reserve4 not between", value1, value2, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5IsNull() {
            addCriterion("system_reserve5 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5IsNotNull() {
            addCriterion("system_reserve5 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5EqualTo(String value) {
            addCriterion("system_reserve5 =", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotEqualTo(String value) {
            addCriterion("system_reserve5 <>", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5GreaterThan(String value) {
            addCriterion("system_reserve5 >", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve5 >=", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5LessThan(String value) {
            addCriterion("system_reserve5 <", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5LessThanOrEqualTo(String value) {
            addCriterion("system_reserve5 <=", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5Like(String value) {
            addCriterion("system_reserve5 like", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotLike(String value) {
            addCriterion("system_reserve5 not like", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5In(List<String> values) {
            addCriterion("system_reserve5 in", values, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotIn(List<String> values) {
            addCriterion("system_reserve5 not in", values, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5Between(String value1, String value2) {
            addCriterion("system_reserve5 between", value1, value2, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotBetween(String value1, String value2) {
            addCriterion("system_reserve5 not between", value1, value2, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgIsNull() {
            addCriterion("del_flg is null");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgIsNotNull() {
            addCriterion("del_flg is not null");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgEqualTo(String value) {
            addCriterion("del_flg =", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotEqualTo(String value) {
            addCriterion("del_flg <>", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgGreaterThan(String value) {
            addCriterion("del_flg >", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("del_flg >=", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgLessThan(String value) {
            addCriterion("del_flg <", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgLessThanOrEqualTo(String value) {
            addCriterion("del_flg <=", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgLike(String value) {
            addCriterion("del_flg like", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotLike(String value) {
            addCriterion("del_flg not like", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgIn(List<String> values) {
            addCriterion("del_flg in", values, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotIn(List<String> values) {
            addCriterion("del_flg not in", values, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgBetween(String value1, String value2) {
            addCriterion("del_flg between", value1, value2, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotBetween(String value1, String value2) {
            addCriterion("del_flg not between", value1, value2, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspIsNull() {
            addCriterion("sys_reg_tmsp is null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspIsNotNull() {
            addCriterion("sys_reg_tmsp is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspEqualTo(Date value) {
            addCriterion("sys_reg_tmsp =", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspNotEqualTo(Date value) {
            addCriterion("sys_reg_tmsp <>", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspGreaterThan(Date value) {
            addCriterion("sys_reg_tmsp >", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_reg_tmsp >=", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspLessThan(Date value) {
            addCriterion("sys_reg_tmsp <", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspLessThanOrEqualTo(Date value) {
            addCriterion("sys_reg_tmsp <=", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspIn(List<Date> values) {
            addCriterion("sys_reg_tmsp in", values, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspNotIn(List<Date> values) {
            addCriterion("sys_reg_tmsp not in", values, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspBetween(Date value1, Date value2) {
            addCriterion("sys_reg_tmsp between", value1, value2, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspNotBetween(Date value1, Date value2) {
            addCriterion("sys_reg_tmsp not between", value1, value2, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdIsNull() {
            addCriterion("sys_reg_usr_cd is null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdIsNotNull() {
            addCriterion("sys_reg_usr_cd is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdEqualTo(String value) {
            addCriterion("sys_reg_usr_cd =", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotEqualTo(String value) {
            addCriterion("sys_reg_usr_cd <>", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdGreaterThan(String value) {
            addCriterion("sys_reg_usr_cd >", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_reg_usr_cd >=", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdLessThan(String value) {
            addCriterion("sys_reg_usr_cd <", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdLessThanOrEqualTo(String value) {
            addCriterion("sys_reg_usr_cd <=", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdLike(String value) {
            addCriterion("sys_reg_usr_cd like", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotLike(String value) {
            addCriterion("sys_reg_usr_cd not like", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdIn(List<String> values) {
            addCriterion("sys_reg_usr_cd in", values, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotIn(List<String> values) {
            addCriterion("sys_reg_usr_cd not in", values, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdBetween(String value1, String value2) {
            addCriterion("sys_reg_usr_cd between", value1, value2, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotBetween(String value1, String value2) {
            addCriterion("sys_reg_usr_cd not between", value1, value2, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspIsNull() {
            addCriterion("sys_upd_tmsp is null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspIsNotNull() {
            addCriterion("sys_upd_tmsp is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspEqualTo(Date value) {
            addCriterion("sys_upd_tmsp =", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspNotEqualTo(Date value) {
            addCriterion("sys_upd_tmsp <>", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspGreaterThan(Date value) {
            addCriterion("sys_upd_tmsp >", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_upd_tmsp >=", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspLessThan(Date value) {
            addCriterion("sys_upd_tmsp <", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspLessThanOrEqualTo(Date value) {
            addCriterion("sys_upd_tmsp <=", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspIn(List<Date> values) {
            addCriterion("sys_upd_tmsp in", values, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspNotIn(List<Date> values) {
            addCriterion("sys_upd_tmsp not in", values, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspBetween(Date value1, Date value2) {
            addCriterion("sys_upd_tmsp between", value1, value2, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspNotBetween(Date value1, Date value2) {
            addCriterion("sys_upd_tmsp not between", value1, value2, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdIsNull() {
            addCriterion("sys_upd_usr_cd is null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdIsNotNull() {
            addCriterion("sys_upd_usr_cd is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdEqualTo(String value) {
            addCriterion("sys_upd_usr_cd =", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotEqualTo(String value) {
            addCriterion("sys_upd_usr_cd <>", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdGreaterThan(String value) {
            addCriterion("sys_upd_usr_cd >", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_upd_usr_cd >=", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdLessThan(String value) {
            addCriterion("sys_upd_usr_cd <", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdLessThanOrEqualTo(String value) {
            addCriterion("sys_upd_usr_cd <=", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdLike(String value) {
            addCriterion("sys_upd_usr_cd like", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotLike(String value) {
            addCriterion("sys_upd_usr_cd not like", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdIn(List<String> values) {
            addCriterion("sys_upd_usr_cd in", values, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotIn(List<String> values) {
            addCriterion("sys_upd_usr_cd not in", values, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdBetween(String value1, String value2) {
            addCriterion("sys_upd_usr_cd between", value1, value2, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotBetween(String value1, String value2) {
            addCriterion("sys_upd_usr_cd not between", value1, value2, "sysUpdUsrCd");
            return (Criteria)this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_auth_user_role
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;
        
        private Object value;
        
        private Object secondValue;
        
        private boolean noValue;
        
        private boolean singleValue;
        
        private boolean betweenValue;
        
        private boolean listValue;
        
        private String typeHandler;
        
        public String getCondition() {
            return condition;
        }
        
        public Object getValue() {
            return value;
        }
        
        public Object getSecondValue() {
            return secondValue;
        }
        
        public boolean isNoValue() {
            return noValue;
        }
        
        public boolean isSingleValue() {
            return singleValue;
        }
        
        public boolean isBetweenValue() {
            return betweenValue;
        }
        
        public boolean isListValue() {
            return listValue;
        }
        
        public String getTypeHandler() {
            return typeHandler;
        }
        
        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }
        
        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            }
            else {
                this.singleValue = true;
            }
        }
        
        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }
        
        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }
        
        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_AUTH_USER_ROLE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(\"ID\") like", value.toUpperCase(), "id");
            return this;
        }

        public Criteria andUserIdLikeInsensitive(String value) {
            addCriterion("upper(\"USER_ID\") like", value.toUpperCase(), "userId");
            return this;
        }

        public Criteria andRoleIdLikeInsensitive(String value) {
            addCriterion("upper(\"ROLE_ID\") like", value.toUpperCase(), "roleId");
            return this;
        }

        public Criteria andSystemReserve1LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE1\") like", value.toUpperCase(), "systemReserve1");
            return this;
        }

        public Criteria andSystemReserve2LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE2\") like", value.toUpperCase(), "systemReserve2");
            return this;
        }

        public Criteria andSystemReserve3LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE3\") like", value.toUpperCase(), "systemReserve3");
            return this;
        }

        public Criteria andSystemReserve4LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE4\") like", value.toUpperCase(), "systemReserve4");
            return this;
        }

        public Criteria andSystemReserve5LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE5\") like", value.toUpperCase(), "systemReserve5");
            return this;
        }

        public Criteria andDelFlgLikeInsensitive(String value) {
            addCriterion("upper(\"DEL_FLG\") like", value.toUpperCase(), "delFlg");
            return this;
        }

        public Criteria andSysRegUsrCdLikeInsensitive(String value) {
            addCriterion("upper(\"SYS_REG_USR_CD\") like", value.toUpperCase(), "sysRegUsrCd");
            return this;
        }

        public Criteria andSysUpdUsrCdLikeInsensitive(String value) {
            addCriterion("upper(\"SYS_UPD_USR_CD\") like", value.toUpperCase(), "sysUpdUsrCd");
            return this;
        }
    }
}