package com.ssmssm.entity.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.ssmssm.entity.Page;

public class UserCriteria {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_user
     * @mbggenerated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_user
     * @mbggenerated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_user
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_auth_user
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public UserCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_auth_user
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;
        
        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }
        
        public boolean isValid() {
            return criteria.size() > 0;
        }
        
        public List<Criterion> getAllCriteria() {
            return criteria;
        }
        
        public List<Criterion> getCriteria() {
            return criteria;
        }
        
        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }
        
        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }
        
        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }
        
        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria)this;
        }
        
        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria)this;
        }
        
        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria)this;
        }
        
        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria)this;
        }
        
        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria)this;
        }
        
        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria)this;
        }
        
        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria)this;
        }
        
        public Criteria andUserPswIsNull() {
            addCriterion("user_psw is null");
            return (Criteria)this;
        }
        
        public Criteria andUserPswIsNotNull() {
            addCriterion("user_psw is not null");
            return (Criteria)this;
        }
        
        public Criteria andUserPswEqualTo(String value) {
            addCriterion("user_psw =", value, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswNotEqualTo(String value) {
            addCriterion("user_psw <>", value, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswGreaterThan(String value) {
            addCriterion("user_psw >", value, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswGreaterThanOrEqualTo(String value) {
            addCriterion("user_psw >=", value, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswLessThan(String value) {
            addCriterion("user_psw <", value, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswLessThanOrEqualTo(String value) {
            addCriterion("user_psw <=", value, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswLike(String value) {
            addCriterion("user_psw like", value, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswNotLike(String value) {
            addCriterion("user_psw not like", value, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswIn(List<String> values) {
            addCriterion("user_psw in", values, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswNotIn(List<String> values) {
            addCriterion("user_psw not in", values, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswBetween(String value1, String value2) {
            addCriterion("user_psw between", value1, value2, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserPswNotBetween(String value1, String value2) {
            addCriterion("user_psw not between", value1, value2, "userPsw");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeIsNull() {
            addCriterion("user_type is null");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeIsNotNull() {
            addCriterion("user_type is not null");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeEqualTo(Short value) {
            addCriterion("user_type =", value, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeNotEqualTo(Short value) {
            addCriterion("user_type <>", value, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeGreaterThan(Short value) {
            addCriterion("user_type >", value, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("user_type >=", value, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeLessThan(Short value) {
            addCriterion("user_type <", value, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeLessThanOrEqualTo(Short value) {
            addCriterion("user_type <=", value, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeIn(List<Short> values) {
            addCriterion("user_type in", values, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeNotIn(List<Short> values) {
            addCriterion("user_type not in", values, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeBetween(Short value1, Short value2) {
            addCriterion("user_type between", value1, value2, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserTypeNotBetween(Short value1, Short value2) {
            addCriterion("user_type not between", value1, value2, "userType");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledIsNull() {
            addCriterion("user_enabled is null");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledIsNotNull() {
            addCriterion("user_enabled is not null");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledEqualTo(Short value) {
            addCriterion("user_enabled =", value, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledNotEqualTo(Short value) {
            addCriterion("user_enabled <>", value, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledGreaterThan(Short value) {
            addCriterion("user_enabled >", value, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledGreaterThanOrEqualTo(Short value) {
            addCriterion("user_enabled >=", value, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledLessThan(Short value) {
            addCriterion("user_enabled <", value, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledLessThanOrEqualTo(Short value) {
            addCriterion("user_enabled <=", value, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledIn(List<Short> values) {
            addCriterion("user_enabled in", values, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledNotIn(List<Short> values) {
            addCriterion("user_enabled not in", values, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledBetween(Short value1, Short value2) {
            addCriterion("user_enabled between", value1, value2, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andUserEnabledNotBetween(Short value1, Short value2) {
            addCriterion("user_enabled not between", value1, value2, "userEnabled");
            return (Criteria)this;
        }
        
        public Criteria andFullNameIsNull() {
            addCriterion("full_name is null");
            return (Criteria)this;
        }
        
        public Criteria andFullNameIsNotNull() {
            addCriterion("full_name is not null");
            return (Criteria)this;
        }
        
        public Criteria andFullNameEqualTo(String value) {
            addCriterion("full_name =", value, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameNotEqualTo(String value) {
            addCriterion("full_name <>", value, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameGreaterThan(String value) {
            addCriterion("full_name >", value, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameGreaterThanOrEqualTo(String value) {
            addCriterion("full_name >=", value, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameLessThan(String value) {
            addCriterion("full_name <", value, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameLessThanOrEqualTo(String value) {
            addCriterion("full_name <=", value, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameLike(String value) {
            addCriterion("full_name like", value, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameNotLike(String value) {
            addCriterion("full_name not like", value, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameIn(List<String> values) {
            addCriterion("full_name in", values, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameNotIn(List<String> values) {
            addCriterion("full_name not in", values, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameBetween(String value1, String value2) {
            addCriterion("full_name between", value1, value2, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andFullNameNotBetween(String value1, String value2) {
            addCriterion("full_name not between", value1, value2, "fullName");
            return (Criteria)this;
        }
        
        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria)this;
        }
        
        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria)this;
        }
        
        public Criteria andSexEqualTo(Short value) {
            addCriterion("sex =", value, "sex");
            return (Criteria)this;
        }
        
        public Criteria andSexNotEqualTo(Short value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria)this;
        }
        
        public Criteria andSexGreaterThan(Short value) {
            addCriterion("sex >", value, "sex");
            return (Criteria)this;
        }
        
        public Criteria andSexGreaterThanOrEqualTo(Short value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria)this;
        }
        
        public Criteria andSexLessThan(Short value) {
            addCriterion("sex <", value, "sex");
            return (Criteria)this;
        }
        
        public Criteria andSexLessThanOrEqualTo(Short value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria)this;
        }
        
        public Criteria andSexIn(List<Short> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria)this;
        }
        
        public Criteria andSexNotIn(List<Short> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria)this;
        }
        
        public Criteria andSexBetween(Short value1, Short value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria)this;
        }
        
        public Criteria andSexNotBetween(Short value1, Short value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria)this;
        }
        
        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria)this;
        }
        
        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria)this;
        }
        
        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria)this;
        }
        
        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneIsNull() {
            addCriterion("mobile_phone is null");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("mobile_phone is not null");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneEqualTo(Long value) {
            addCriterion("mobile_phone =", value, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneNotEqualTo(Long value) {
            addCriterion("mobile_phone <>", value, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneGreaterThan(Long value) {
            addCriterion("mobile_phone >", value, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneGreaterThanOrEqualTo(Long value) {
            addCriterion("mobile_phone >=", value, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneLessThan(Long value) {
            addCriterion("mobile_phone <", value, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneLessThanOrEqualTo(Long value) {
            addCriterion("mobile_phone <=", value, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneIn(List<Long> values) {
            addCriterion("mobile_phone in", values, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneNotIn(List<Long> values) {
            addCriterion("mobile_phone not in", values, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneBetween(Long value1, Long value2) {
            addCriterion("mobile_phone between", value1, value2, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andMobilePhoneNotBetween(Long value1, Long value2) {
            addCriterion("mobile_phone not between", value1, value2, "mobilePhone");
            return (Criteria)this;
        }
        
        public Criteria andCommentsIsNull() {
            addCriterion("comments is null");
            return (Criteria)this;
        }
        
        public Criteria andCommentsIsNotNull() {
            addCriterion("comments is not null");
            return (Criteria)this;
        }
        
        public Criteria andCommentsEqualTo(String value) {
            addCriterion("comments =", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("comments <>", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("comments >", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("comments >=", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsLessThan(String value) {
            addCriterion("comments <", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("comments <=", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsLike(String value) {
            addCriterion("comments like", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsNotLike(String value) {
            addCriterion("comments not like", value, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsIn(List<String> values) {
            addCriterion("comments in", values, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("comments not in", values, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("comments between", value1, value2, "comments");
            return (Criteria)this;
        }
        
        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("comments not between", value1, value2, "comments");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureIsNull() {
            addCriterion("head_sculpture is null");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureIsNotNull() {
            addCriterion("head_sculpture is not null");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureEqualTo(String value) {
            addCriterion("head_sculpture =", value, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureNotEqualTo(String value) {
            addCriterion("head_sculpture <>", value, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureGreaterThan(String value) {
            addCriterion("head_sculpture >", value, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureGreaterThanOrEqualTo(String value) {
            addCriterion("head_sculpture >=", value, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureLessThan(String value) {
            addCriterion("head_sculpture <", value, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureLessThanOrEqualTo(String value) {
            addCriterion("head_sculpture <=", value, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureLike(String value) {
            addCriterion("head_sculpture like", value, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureNotLike(String value) {
            addCriterion("head_sculpture not like", value, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureIn(List<String> values) {
            addCriterion("head_sculpture in", values, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureNotIn(List<String> values) {
            addCriterion("head_sculpture not in", values, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureBetween(String value1, String value2) {
            addCriterion("head_sculpture between", value1, value2, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andHeadSculptureNotBetween(String value1, String value2) {
            addCriterion("head_sculpture not between", value1, value2, "headSculpture");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1IsNull() {
            addCriterion("system_reserve1 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1IsNotNull() {
            addCriterion("system_reserve1 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1EqualTo(String value) {
            addCriterion("system_reserve1 =", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotEqualTo(String value) {
            addCriterion("system_reserve1 <>", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1GreaterThan(String value) {
            addCriterion("system_reserve1 >", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve1 >=", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1LessThan(String value) {
            addCriterion("system_reserve1 <", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1LessThanOrEqualTo(String value) {
            addCriterion("system_reserve1 <=", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1Like(String value) {
            addCriterion("system_reserve1 like", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotLike(String value) {
            addCriterion("system_reserve1 not like", value, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1In(List<String> values) {
            addCriterion("system_reserve1 in", values, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotIn(List<String> values) {
            addCriterion("system_reserve1 not in", values, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1Between(String value1, String value2) {
            addCriterion("system_reserve1 between", value1, value2, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve1NotBetween(String value1, String value2) {
            addCriterion("system_reserve1 not between", value1, value2, "systemReserve1");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2IsNull() {
            addCriterion("system_reserve2 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2IsNotNull() {
            addCriterion("system_reserve2 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2EqualTo(String value) {
            addCriterion("system_reserve2 =", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotEqualTo(String value) {
            addCriterion("system_reserve2 <>", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2GreaterThan(String value) {
            addCriterion("system_reserve2 >", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve2 >=", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2LessThan(String value) {
            addCriterion("system_reserve2 <", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2LessThanOrEqualTo(String value) {
            addCriterion("system_reserve2 <=", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2Like(String value) {
            addCriterion("system_reserve2 like", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotLike(String value) {
            addCriterion("system_reserve2 not like", value, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2In(List<String> values) {
            addCriterion("system_reserve2 in", values, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotIn(List<String> values) {
            addCriterion("system_reserve2 not in", values, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2Between(String value1, String value2) {
            addCriterion("system_reserve2 between", value1, value2, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve2NotBetween(String value1, String value2) {
            addCriterion("system_reserve2 not between", value1, value2, "systemReserve2");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3IsNull() {
            addCriterion("system_reserve3 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3IsNotNull() {
            addCriterion("system_reserve3 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3EqualTo(String value) {
            addCriterion("system_reserve3 =", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotEqualTo(String value) {
            addCriterion("system_reserve3 <>", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3GreaterThan(String value) {
            addCriterion("system_reserve3 >", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve3 >=", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3LessThan(String value) {
            addCriterion("system_reserve3 <", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3LessThanOrEqualTo(String value) {
            addCriterion("system_reserve3 <=", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3Like(String value) {
            addCriterion("system_reserve3 like", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotLike(String value) {
            addCriterion("system_reserve3 not like", value, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3In(List<String> values) {
            addCriterion("system_reserve3 in", values, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotIn(List<String> values) {
            addCriterion("system_reserve3 not in", values, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3Between(String value1, String value2) {
            addCriterion("system_reserve3 between", value1, value2, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve3NotBetween(String value1, String value2) {
            addCriterion("system_reserve3 not between", value1, value2, "systemReserve3");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4IsNull() {
            addCriterion("system_reserve4 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4IsNotNull() {
            addCriterion("system_reserve4 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4EqualTo(String value) {
            addCriterion("system_reserve4 =", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotEqualTo(String value) {
            addCriterion("system_reserve4 <>", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4GreaterThan(String value) {
            addCriterion("system_reserve4 >", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve4 >=", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4LessThan(String value) {
            addCriterion("system_reserve4 <", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4LessThanOrEqualTo(String value) {
            addCriterion("system_reserve4 <=", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4Like(String value) {
            addCriterion("system_reserve4 like", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotLike(String value) {
            addCriterion("system_reserve4 not like", value, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4In(List<String> values) {
            addCriterion("system_reserve4 in", values, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotIn(List<String> values) {
            addCriterion("system_reserve4 not in", values, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4Between(String value1, String value2) {
            addCriterion("system_reserve4 between", value1, value2, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve4NotBetween(String value1, String value2) {
            addCriterion("system_reserve4 not between", value1, value2, "systemReserve4");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5IsNull() {
            addCriterion("system_reserve5 is null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5IsNotNull() {
            addCriterion("system_reserve5 is not null");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5EqualTo(String value) {
            addCriterion("system_reserve5 =", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotEqualTo(String value) {
            addCriterion("system_reserve5 <>", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5GreaterThan(String value) {
            addCriterion("system_reserve5 >", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5GreaterThanOrEqualTo(String value) {
            addCriterion("system_reserve5 >=", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5LessThan(String value) {
            addCriterion("system_reserve5 <", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5LessThanOrEqualTo(String value) {
            addCriterion("system_reserve5 <=", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5Like(String value) {
            addCriterion("system_reserve5 like", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotLike(String value) {
            addCriterion("system_reserve5 not like", value, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5In(List<String> values) {
            addCriterion("system_reserve5 in", values, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotIn(List<String> values) {
            addCriterion("system_reserve5 not in", values, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5Between(String value1, String value2) {
            addCriterion("system_reserve5 between", value1, value2, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andSystemReserve5NotBetween(String value1, String value2) {
            addCriterion("system_reserve5 not between", value1, value2, "systemReserve5");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgIsNull() {
            addCriterion("del_flg is null");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgIsNotNull() {
            addCriterion("del_flg is not null");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgEqualTo(String value) {
            addCriterion("del_flg =", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotEqualTo(String value) {
            addCriterion("del_flg <>", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgGreaterThan(String value) {
            addCriterion("del_flg >", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgGreaterThanOrEqualTo(String value) {
            addCriterion("del_flg >=", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgLessThan(String value) {
            addCriterion("del_flg <", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgLessThanOrEqualTo(String value) {
            addCriterion("del_flg <=", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgLike(String value) {
            addCriterion("del_flg like", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotLike(String value) {
            addCriterion("del_flg not like", value, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgIn(List<String> values) {
            addCriterion("del_flg in", values, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotIn(List<String> values) {
            addCriterion("del_flg not in", values, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgBetween(String value1, String value2) {
            addCriterion("del_flg between", value1, value2, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andDelFlgNotBetween(String value1, String value2) {
            addCriterion("del_flg not between", value1, value2, "delFlg");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspIsNull() {
            addCriterion("sys_reg_tmsp is null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspIsNotNull() {
            addCriterion("sys_reg_tmsp is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspEqualTo(Date value) {
            addCriterion("sys_reg_tmsp =", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspNotEqualTo(Date value) {
            addCriterion("sys_reg_tmsp <>", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspGreaterThan(Date value) {
            addCriterion("sys_reg_tmsp >", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_reg_tmsp >=", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspLessThan(Date value) {
            addCriterion("sys_reg_tmsp <", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspLessThanOrEqualTo(Date value) {
            addCriterion("sys_reg_tmsp <=", value, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspIn(List<Date> values) {
            addCriterion("sys_reg_tmsp in", values, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspNotIn(List<Date> values) {
            addCriterion("sys_reg_tmsp not in", values, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspBetween(Date value1, Date value2) {
            addCriterion("sys_reg_tmsp between", value1, value2, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegTmspNotBetween(Date value1, Date value2) {
            addCriterion("sys_reg_tmsp not between", value1, value2, "sysRegTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdIsNull() {
            addCriterion("sys_reg_usr_cd is null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdIsNotNull() {
            addCriterion("sys_reg_usr_cd is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdEqualTo(String value) {
            addCriterion("sys_reg_usr_cd =", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotEqualTo(String value) {
            addCriterion("sys_reg_usr_cd <>", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdGreaterThan(String value) {
            addCriterion("sys_reg_usr_cd >", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_reg_usr_cd >=", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdLessThan(String value) {
            addCriterion("sys_reg_usr_cd <", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdLessThanOrEqualTo(String value) {
            addCriterion("sys_reg_usr_cd <=", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdLike(String value) {
            addCriterion("sys_reg_usr_cd like", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotLike(String value) {
            addCriterion("sys_reg_usr_cd not like", value, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdIn(List<String> values) {
            addCriterion("sys_reg_usr_cd in", values, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotIn(List<String> values) {
            addCriterion("sys_reg_usr_cd not in", values, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdBetween(String value1, String value2) {
            addCriterion("sys_reg_usr_cd between", value1, value2, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysRegUsrCdNotBetween(String value1, String value2) {
            addCriterion("sys_reg_usr_cd not between", value1, value2, "sysRegUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspIsNull() {
            addCriterion("sys_upd_tmsp is null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspIsNotNull() {
            addCriterion("sys_upd_tmsp is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspEqualTo(Date value) {
            addCriterion("sys_upd_tmsp =", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspNotEqualTo(Date value) {
            addCriterion("sys_upd_tmsp <>", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspGreaterThan(Date value) {
            addCriterion("sys_upd_tmsp >", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_upd_tmsp >=", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspLessThan(Date value) {
            addCriterion("sys_upd_tmsp <", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspLessThanOrEqualTo(Date value) {
            addCriterion("sys_upd_tmsp <=", value, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspIn(List<Date> values) {
            addCriterion("sys_upd_tmsp in", values, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspNotIn(List<Date> values) {
            addCriterion("sys_upd_tmsp not in", values, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspBetween(Date value1, Date value2) {
            addCriterion("sys_upd_tmsp between", value1, value2, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdTmspNotBetween(Date value1, Date value2) {
            addCriterion("sys_upd_tmsp not between", value1, value2, "sysUpdTmsp");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdIsNull() {
            addCriterion("sys_upd_usr_cd is null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdIsNotNull() {
            addCriterion("sys_upd_usr_cd is not null");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdEqualTo(String value) {
            addCriterion("sys_upd_usr_cd =", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotEqualTo(String value) {
            addCriterion("sys_upd_usr_cd <>", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdGreaterThan(String value) {
            addCriterion("sys_upd_usr_cd >", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_upd_usr_cd >=", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdLessThan(String value) {
            addCriterion("sys_upd_usr_cd <", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdLessThanOrEqualTo(String value) {
            addCriterion("sys_upd_usr_cd <=", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdLike(String value) {
            addCriterion("sys_upd_usr_cd like", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotLike(String value) {
            addCriterion("sys_upd_usr_cd not like", value, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdIn(List<String> values) {
            addCriterion("sys_upd_usr_cd in", values, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotIn(List<String> values) {
            addCriterion("sys_upd_usr_cd not in", values, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdBetween(String value1, String value2) {
            addCriterion("sys_upd_usr_cd between", value1, value2, "sysUpdUsrCd");
            return (Criteria)this;
        }
        
        public Criteria andSysUpdUsrCdNotBetween(String value1, String value2) {
            addCriterion("sys_upd_usr_cd not between", value1, value2, "sysUpdUsrCd");
            return (Criteria)this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_auth_user
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;
        
        private Object value;
        
        private Object secondValue;
        
        private boolean noValue;
        
        private boolean singleValue;
        
        private boolean betweenValue;
        
        private boolean listValue;
        
        private String typeHandler;
        
        public String getCondition() {
            return condition;
        }
        
        public Object getValue() {
            return value;
        }
        
        public Object getSecondValue() {
            return secondValue;
        }
        
        public boolean isNoValue() {
            return noValue;
        }
        
        public boolean isSingleValue() {
            return singleValue;
        }
        
        public boolean isBetweenValue() {
            return betweenValue;
        }
        
        public boolean isListValue() {
            return listValue;
        }
        
        public String getTypeHandler() {
            return typeHandler;
        }
        
        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }
        
        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            }
            else {
                this.singleValue = true;
            }
        }
        
        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }
        
        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }
        
        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_AUTH_USER
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andIdLikeInsensitive(String value) {
            addCriterion("upper(\"ID\") like", value.toUpperCase(), "id");
            return this;
        }

        public Criteria andUserNameLikeInsensitive(String value) {
            addCriterion("upper(\"USER_NAME\") like", value.toUpperCase(), "userName");
            return this;
        }

        public Criteria andUserPswLikeInsensitive(String value) {
            addCriterion("upper(\"USER_PSW\") like", value.toUpperCase(), "userPsw");
            return this;
        }

        public Criteria andFullNameLikeInsensitive(String value) {
            addCriterion("upper(\"FULL_NAME\") like", value.toUpperCase(), "fullName");
            return this;
        }

        public Criteria andEmailLikeInsensitive(String value) {
            addCriterion("upper(\"EMAIL\") like", value.toUpperCase(), "email");
            return this;
        }

        public Criteria andCommentsLikeInsensitive(String value) {
            addCriterion("upper(\"COMMENTS\") like", value.toUpperCase(), "comments");
            return this;
        }

        public Criteria andHeadSculptureLikeInsensitive(String value) {
            addCriterion("upper(\"HEAD_SCULPTURE\") like", value.toUpperCase(), "headSculpture");
            return this;
        }

        public Criteria andSystemReserve1LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE1\") like", value.toUpperCase(), "systemReserve1");
            return this;
        }

        public Criteria andSystemReserve2LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE2\") like", value.toUpperCase(), "systemReserve2");
            return this;
        }

        public Criteria andSystemReserve3LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE3\") like", value.toUpperCase(), "systemReserve3");
            return this;
        }

        public Criteria andSystemReserve4LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE4\") like", value.toUpperCase(), "systemReserve4");
            return this;
        }

        public Criteria andSystemReserve5LikeInsensitive(String value) {
            addCriterion("upper(\"SYSTEM_RESERVE5\") like", value.toUpperCase(), "systemReserve5");
            return this;
        }

        public Criteria andDelFlgLikeInsensitive(String value) {
            addCriterion("upper(\"DEL_FLG\") like", value.toUpperCase(), "delFlg");
            return this;
        }

        public Criteria andSysRegUsrCdLikeInsensitive(String value) {
            addCriterion("upper(\"SYS_REG_USR_CD\") like", value.toUpperCase(), "sysRegUsrCd");
            return this;
        }

        public Criteria andSysUpdUsrCdLikeInsensitive(String value) {
            addCriterion("upper(\"SYS_UPD_USR_CD\") like", value.toUpperCase(), "sysUpdUsrCd");
            return this;
        }
    }
}